export default async function handler(req, res) {
  res.setHeader("Cache-Control", "s-maxage=3600, stale-while-revalidate");
  return res.status(200).json({ stocks: SAUDI_STOCKS, source: "official", total: SAUDI_STOCKS.length });
}

const SAUDI_STOCKS = [
  // الطاقة
  { symbol: "2222.SR", name: "أرامكو السعودية", sector: "الطاقة" },
  { symbol: "4030.SR", name: "البحري", sector: "الطاقة" },
  { symbol: "4200.SR", name: "الدريس", sector: "الطاقة" },
  { symbol: "2030.SR", name: "المصافي", sector: "الطاقة" },
  { symbol: "2380.SR", name: "بترو رابغ", sector: "الطاقة" },
  { symbol: "2381.SR", name: "الحفر العربية", sector: "الطاقة" },
  // المواد الأساسية
  { symbol: "3092.SR", name: "أسمنت الرياض", sector: "المواد الأساسية" },
  { symbol: "1320.SR", name: "أنابيب السعودية", sector: "المواد الأساسية" },
  { symbol: "1321.SR", name: "أنابيب الشرق", sector: "المواد الأساسية" },
  { symbol: "2300.SR", name: "صناعة الورق", sector: "المواد الأساسية" },
  { symbol: "2010.SR", name: "سابك", sector: "المواد الأساسية" },
  { symbol: "2200.SR", name: "أنابيب", sector: "المواد الأساسية" },
  { symbol: "2330.SR", name: "المتقدمة", sector: "المواد الأساسية" },
  { symbol: "2220.SR", name: "معدنية", sector: "المواد الأساسية" },
  { symbol: "2002.SR", name: "بتروكيم", sector: "المواد الأساسية" },
  { symbol: "2250.SR", name: "المجموعة السعودية", sector: "المواد الأساسية" },
  { symbol: "3091.SR", name: "أسمنت الجوف", sector: "المواد الأساسية" },
  { symbol: "3040.SR", name: "أسمنت القصيم", sector: "المواد الأساسية" },
  { symbol: "3003.SR", name: "أسمنت المدينة", sector: "المواد الأساسية" },
  { symbol: "3050.SR", name: "أسمنت الجنوب", sector: "المواد الأساسية" },
  { symbol: "3080.SR", name: "أسمنت الشرقية", sector: "المواد الأساسية" },
  { symbol: "3004.SR", name: "أسمنت الشمالية", sector: "المواد الأساسية" },
  { symbol: "3020.SR", name: "أسمنت اليمامة", sector: "المواد الأساسية" },
  { symbol: "3005.SR", name: "إسمنت أم القرى", sector: "المواد الأساسية" },
  { symbol: "3090.SR", name: "أسمنت تبوك", sector: "المواد الأساسية" },
  { symbol: "3001.SR", name: "أسمنت حائل", sector: "المواد الأساسية" },
  { symbol: "3002.SR", name: "أسمنت نجران", sector: "المواد الأساسية" },
  { symbol: "3060.SR", name: "أسمنت ينبع", sector: "المواد الأساسية" },
  { symbol: "1301.SR", name: "أسلاك", sector: "المواد الأساسية" },
  { symbol: "2020.SR", name: "سافكو", sector: "المواد الأساسية" },
  { symbol: "3030.SR", name: "أسمنت السعودية", sector: "المواد الأساسية" },
  { symbol: "3010.SR", name: "أسمنت العربية", sector: "المواد الأساسية" },
  { symbol: "2060.SR", name: "التصنيع", sector: "المواد الأساسية" },
  { symbol: "1211.SR", name: "معادن", sector: "المواد الأساسية" },
  { symbol: "2090.SR", name: "جبسكو", sector: "المواد الأساسية" },
  { symbol: "2240.SR", name: "الزامل للصناعة", sector: "المواد الأساسية" },
  { symbol: "1202.SR", name: "مبكو", sector: "المواد الأساسية" },
  { symbol: "2310.SR", name: "سبكيم العالمية", sector: "المواد الأساسية" },
  { symbol: "2150.SR", name: "زجاج", sector: "المواد الأساسية" },
  { symbol: "1210.SR", name: "بي سي آي", sector: "المواد الأساسية" },
  { symbol: "3008.SR", name: "الكثيري", sector: "المواد الأساسية" },
  { symbol: "2170.SR", name: "اللجين", sector: "المواد الأساسية" },
  { symbol: "1304.SR", name: "اليمامة للحديد", sector: "المواد الأساسية" },
  { symbol: "2180.SR", name: "فيبكو", sector: "المواد الأساسية" },
  { symbol: "1201.SR", name: "تكوين", sector: "المواد الأساسية" },
  { symbol: "3007.SR", name: "الواحة", sector: "المواد الأساسية" },
  { symbol: "2350.SR", name: "كيان السعودية", sector: "المواد الأساسية" },
  { symbol: "2001.SR", name: "كيمانول", sector: "المواد الأساسية" },
  { symbol: "2210.SR", name: "نماء للكيماويات", sector: "المواد الأساسية" },
  { symbol: "2290.SR", name: "ينساب", sector: "المواد الأساسية" },
  // السلع الرأسمالية
  { symbol: "2360.SR", name: "الفخارية", sector: "السلع الرأسمالية" },
  { symbol: "4140.SR", name: "صادرات", sector: "السلع الرأسمالية" },
  { symbol: "1330.SR", name: "الخضري", sector: "السلع الرأسمالية" },
  { symbol: "2160.SR", name: "أميانتيت", sector: "السلع الرأسمالية" },
  { symbol: "2140.SR", name: "أيان", sector: "السلع الرأسمالية" },
  { symbol: "2320.SR", name: "البابطين", sector: "السلع الرأسمالية" },
  { symbol: "2040.SR", name: "الخزف السعودي", sector: "السلع الرأسمالية" },
  { symbol: "2370.SR", name: "مسك", sector: "السلع الرأسمالية" },
  { symbol: "1303.SR", name: "الصناعات الكهربائية", sector: "السلع الرأسمالية" },
  { symbol: "4141.SR", name: "العمران", sector: "السلع الرأسمالية" },
  { symbol: "2110.SR", name: "الكابلات السعودية", sector: "السلع الرأسمالية" },
  { symbol: "1302.SR", name: "بوان", sector: "السلع الرأسمالية" },
  { symbol: "1212.SR", name: "أسترا الصناعية", sector: "السلع الرأسمالية" },
  // الخدمات التجارية والمهنية
  { symbol: "4270.SR", name: "طباعة وتغليف", sector: "الخدمات التجارية" },
  { symbol: "6004.SR", name: "التموين", sector: "الخدمات التجارية" },
  { symbol: "1831.SR", name: "مهارة", sector: "الخدمات التجارية" },
  { symbol: "1832.SR", name: "الصمعاني", sector: "الخدمات التجارية" },
  // النقل
  { symbol: "4031.SR", name: "الخدمات الأرضية", sector: "النقل" },
  { symbol: "2190.SR", name: "سيسكو", sector: "النقل" },
  { symbol: "4040.SR", name: "سابتكو", sector: "النقل" },
  { symbol: "4260.SR", name: "بدجت السعودية", sector: "النقل" },
  { symbol: "4261.SR", name: "ذيب", sector: "النقل" },
  { symbol: "4110.SR", name: "باتك", sector: "النقل" },
  // السلع طويلة الأجل
  { symbol: "2130.SR", name: "صدق", sector: "السلع طويلة الأجل" },
  { symbol: "2340.SR", name: "العبداللطيف", sector: "السلع طويلة الأجل" },
  { symbol: "4012.SR", name: "الأصيل", sector: "السلع طويلة الأجل" },
  { symbol: "4011.SR", name: "لازوردي", sector: "السلع طويلة الأجل" },
  { symbol: "1213.SR", name: "نسيج", sector: "السلع طويلة الأجل" },
  { symbol: "4180.SR", name: "مجموعة فتيحي", sector: "السلع طويلة الأجل" },
  // الخدمات الاستهلاكية
  { symbol: "4291.SR", name: "الوطنية للتعليم", sector: "الخدمات الاستهلاكية" },
  { symbol: "4290.SR", name: "الخليج للتدريب", sector: "الخدمات الاستهلاكية" },
  { symbol: "4170.SR", name: "شمس", sector: "الخدمات الاستهلاكية" },
  { symbol: "4010.SR", name: "دور", sector: "الخدمات الاستهلاكية" },
  { symbol: "6012.SR", name: "ريدان", sector: "الخدمات الاستهلاكية" },
  { symbol: "6013.SR", name: "التطويرية الغذائية", sector: "الخدمات الاستهلاكية" },
  { symbol: "4292.SR", name: "عطاء", sector: "الخدمات الاستهلاكية" },
  { symbol: "1830.SR", name: "وقت اللياقة", sector: "الخدمات الاستهلاكية" },
  { symbol: "6002.SR", name: "هرفي للأغذية", sector: "الخدمات الاستهلاكية" },
  { symbol: "1810.SR", name: "سيرا", sector: "الخدمات الاستهلاكية" },
  { symbol: "1820.SR", name: "مجموعة الحكير", sector: "الخدمات الاستهلاكية" },
  // الإعلام والترفيه
  { symbol: "4210.SR", name: "الأبحاث والتسويق", sector: "الإعلام والترفيه" },
  { symbol: "4070.SR", name: "تهامة", sector: "الإعلام والترفيه" },
  // تجزئة السلع الكمالية
  { symbol: "4050.SR", name: "ساسكو", sector: "التجزئة" },
  { symbol: "4008.SR", name: "ساكو", sector: "التجزئة" },
  { symbol: "4003.SR", name: "إكسترا", sector: "التجزئة" },
  { symbol: "1214.SR", name: "شاكر", sector: "التجزئة" },
  { symbol: "4051.SR", name: "باعظيم", sector: "التجزئة" },
  { symbol: "4190.SR", name: "جرير", sector: "التجزئة" },
  { symbol: "4191.SR", name: "أبو معطي", sector: "التجزئة" },
  { symbol: "4240.SR", name: "الحكير", sector: "التجزئة" },
  // تجزئة الأغذية
  { symbol: "4006.SR", name: "أسواق المزرعة", sector: "تجزئة الأغذية" },
  { symbol: "4160.SR", name: "ثمار", sector: "تجزئة الأغذية" },
  { symbol: "4001.SR", name: "أسواق عبدالله العثيم", sector: "تجزئة الأغذية" },
  { symbol: "4161.SR", name: "بن داود", sector: "تجزئة الأغذية" },
  { symbol: "4061.SR", name: "أنعام القابضة", sector: "تجزئة الأغذية" },
  // إنتاج الأغذية
  { symbol: "6050.SR", name: "الأسماك", sector: "إنتاج الأغذية" },
  { symbol: "2270.SR", name: "سدافكو", sector: "إنتاج الأغذية" },
  { symbol: "6010.SR", name: "نادك", sector: "إنتاج الأغذية" },
  { symbol: "6070.SR", name: "الجوف", sector: "إنتاج الأغذية" },
  { symbol: "6060.SR", name: "الشرقية للتنمية", sector: "إنتاج الأغذية" },
  { symbol: "6020.SR", name: "جاكو", sector: "إنتاج الأغذية" },
  { symbol: "2280.SR", name: "المراعي", sector: "إنتاج الأغذية" },
  { symbol: "6040.SR", name: "تبوك الزراعية", sector: "إنتاج الأغذية" },
  { symbol: "6090.SR", name: "جازادكو", sector: "إنتاج الأغذية" },
  { symbol: "6001.SR", name: "حلواني إخوان", sector: "إنتاج الأغذية" },
  { symbol: "2100.SR", name: "وفرة", sector: "إنتاج الأغذية" },
  { symbol: "2050.SR", name: "مجموعة صافولا", sector: "إنتاج الأغذية" },
  { symbol: "2281.SR", name: "تنمية", sector: "إنتاج الأغذية" },
  // الرعاية الصحية
  { symbol: "2230.SR", name: "الكيميائية", sector: "الرعاية الصحية" },
  { symbol: "4005.SR", name: "رعاية", sector: "الرعاية الصحية" },
  { symbol: "4007.SR", name: "الحمادي", sector: "الرعاية الصحية" },
  { symbol: "4009.SR", name: "المستشفى السعودي الألماني", sector: "الرعاية الصحية" },
  { symbol: "4002.SR", name: "المواساة", sector: "الرعاية الصحية" },
  { symbol: "4004.SR", name: "دله الصحية", sector: "الرعاية الصحية" },
  { symbol: "4013.SR", name: "سليمان الحبيب", sector: "الرعاية الصحية" },
  { symbol: "2070.SR", name: "الدوائية", sector: "الأدوية" },
  // البنوك
  { symbol: "1180.SR", name: "الأهلي", sector: "البنوك" },
  { symbol: "1060.SR", name: "ساب", sector: "البنوك" },
  { symbol: "1050.SR", name: "السعودي الفرنسي", sector: "البنوك" },
  { symbol: "1030.SR", name: "الإستثمار", sector: "البنوك" },
  { symbol: "1080.SR", name: "العربي", sector: "البنوك" },
  { symbol: "1140.SR", name: "البلاد", sector: "البنوك" },
  { symbol: "1020.SR", name: "الجزيرة", sector: "البنوك" },
  { symbol: "1010.SR", name: "الرياض", sector: "البنوك" },
  { symbol: "1182.SR", name: "أملاك", sector: "البنوك" },
  { symbol: "1150.SR", name: "الإنماء", sector: "البنوك" },
  { symbol: "1120.SR", name: "الراجحي", sector: "البنوك" },
  { symbol: "1183.SR", name: "سهل", sector: "البنوك" },
  // الاستثمار والتمويل
  { symbol: "1111.SR", name: "تداول السعودية", sector: "الاستثمار والتمويل" },
  { symbol: "2120.SR", name: "متطورة", sector: "الاستثمار والتمويل" },
  { symbol: "4130.SR", name: "الباحة", sector: "الاستثمار والتمويل" },
  { symbol: "4280.SR", name: "المملكة", sector: "الاستثمار والتمويل" },
  { symbol: "4080.SR", name: "سناد القابضة", sector: "الاستثمار والتمويل" },
  { symbol: "4081.SR", name: "النايفات", sector: "الاستثمار والتمويل" },
  // التأمين
  { symbol: "8010.SR", name: "التعاونية", sector: "التأمين" },
  { symbol: "8260.SR", name: "الخليجية العامة", sector: "التأمين" },
  { symbol: "8110.SR", name: "وفا للتأمين", sector: "التأمين" },
  { symbol: "8200.SR", name: "الإعادة السعودية", sector: "التأمين" },
  { symbol: "8280.SR", name: "العالمية للتأمين", sector: "التأمين" },
  { symbol: "8100.SR", name: "سايكو", sector: "التأمين" },
  { symbol: "8190.SR", name: "المتحدة للتأمين", sector: "التأمين" },
  { symbol: "8300.SR", name: "الوطنية للتأمين", sector: "التأمين" },
  { symbol: "8150.SR", name: "أسيج", sector: "التأمين" },
  { symbol: "8250.SR", name: "اكسا التعاونية", sector: "التأمين" },
  { symbol: "8040.SR", name: "أليانز إس إف", sector: "التأمين" },
  { symbol: "8310.SR", name: "أمانة للتأمين", sector: "التأمين" },
  { symbol: "8120.SR", name: "اتحاد الخليج", sector: "التأمين" },
  { symbol: "8130.SR", name: "الأهلي للتكافل", sector: "التأمين" },
  { symbol: "8312.SR", name: "الإنماء طوكيو م", sector: "التأمين" },
  { symbol: "8170.SR", name: "الاتحاد للتأمين", sector: "التأمين" },
  { symbol: "8160.SR", name: "التأمين العربية", sector: "التأمين" },
  { symbol: "8012.SR", name: "جزيرة تكافل", sector: "التأمين" },
  { symbol: "8070.SR", name: "الدرع العربي", sector: "التأمين" },
  { symbol: "8230.SR", name: "تكافل الراجحي", sector: "التأمين" },
  { symbol: "8180.SR", name: "الصقر للتأمين", sector: "التأمين" },
  { symbol: "8030.SR", name: "ميدغلف للتأمين", sector: "التأمين" },
  { symbol: "8270.SR", name: "بروج للتأمين", sector: "التأمين" },
  { symbol: "8210.SR", name: "بوبا العربية", sector: "التأمين" },
  { symbol: "8240.SR", name: "تشب", sector: "التأمين" },
  { symbol: "8050.SR", name: "سلامة", sector: "التأمين" },
  { symbol: "8290.SR", name: "سوليدرتي تكافل", sector: "التأمين" },
  { symbol: "8311.SR", name: "عناية", sector: "التأمين" },
  { symbol: "8020.SR", name: "ملاذ للتأمين", sector: "التأمين" },
  { symbol: "8060.SR", name: "ولاء", sector: "التأمين" },
  // تقنية المعلومات
  { symbol: "7200.SR", name: "ام آي اس", sector: "تقنية المعلومات" },
  { symbol: "7201.SR", name: "بحر العرب", sector: "تقنية المعلومات" },
  { symbol: "7202.SR", name: "سلوشنز", sector: "تقنية المعلومات" },
  { symbol: "7203.SR", name: "العربية للتقنية", sector: "تقنية المعلومات" },
  { symbol: "7204.SR", name: "نيو ميديا", sector: "تقنية المعلومات" },
  { symbol: "9404.SR", name: "صندوق الإنماء ريت", sector: "صناديق الريت" },
  { symbol: "1324.SR", name: "صالح الراشد", sector: "السلع الرأسمالية" },
  { symbol: "2282.SR", name: "تنمية الغذائية", sector: "إنتاج الأغذية" },
  { symbol: "2283.SR", name: "أسواق المزرعة", sector: "إنتاج الأغذية" },
  // الاتصالات
  { symbol: "7020.SR", name: "إتحاد إتصالات", sector: "الاتصالات" },
  { symbol: "7040.SR", name: "عذيب للإتصالات", sector: "الاتصالات" },
  { symbol: "7010.SR", name: "اس تي سي", sector: "الاتصالات" },
  { symbol: "7030.SR", name: "زين السعودية", sector: "الاتصالات" },
  // المرافق العامة
  { symbol: "5110.SR", name: "كهرباء السعودية", sector: "المرافق العامة" },
  { symbol: "2080.SR", name: "الغاز", sector: "المرافق العامة" },
  { symbol: "2081.SR", name: "المياه", sector: "المرافق العامة" },
  { symbol: "2082.SR", name: "أكوا باور", sector: "المرافق العامة" },
  // صناديق الريت
  { symbol: "4338.SR", name: "الأهلي ريت 1", sector: "صناديق الريت" },
  { symbol: "4331.SR", name: "الجزيرة ريت", sector: "صناديق الريت" },
  { symbol: "4348.SR", name: "الخبير ريت", sector: "صناديق الريت" },
  { symbol: "4340.SR", name: "الراجحي ريت", sector: "صناديق الريت" },
  { symbol: "4330.SR", name: "الرياض ريت", sector: "صناديق الريت" },
  { symbol: "4337.SR", name: "مشاعر ريت", sector: "صناديق الريت" },
  { symbol: "4334.SR", name: "المعذر ريت", sector: "صناديق الريت" },
  { symbol: "4347.SR", name: "بنيان ريت", sector: "صناديق الريت" },
  { symbol: "4333.SR", name: "تعليم ريت", sector: "صناديق الريت" },
  { symbol: "4332.SR", name: "جدوى ريت الحرمين", sector: "صناديق الريت" },
  { symbol: "4342.SR", name: "جدوى ريت السعودية", sector: "صناديق الريت" },
  { symbol: "4339.SR", name: "دراية ريت", sector: "صناديق الريت" },
  { symbol: "4344.SR", name: "سدكو كابيتال ريت", sector: "صناديق الريت" },
  { symbol: "4345.SR", name: "سويكورب وابل ريت", sector: "صناديق الريت" },
  { symbol: "4335.SR", name: "مشاركة ريت", sector: "صناديق الريت" },
  { symbol: "4336.SR", name: "ملكية ريت", sector: "صناديق الريت" },
  { symbol: "4346.SR", name: "ميفك ريت", sector: "صناديق الريت" },
  // العقارات
  { symbol: "4220.SR", name: "إعمار", sector: "العقارات" },
  { symbol: "4020.SR", name: "العقارية", sector: "العقارات" },
  { symbol: "4320.SR", name: "الأندلس", sector: "العقارات" },
  { symbol: "4230.SR", name: "البحر الأحمر", sector: "العقارات" },
  { symbol: "4150.SR", name: "التعمير", sector: "العقارات" },
  { symbol: "4321.SR", name: "المراكز", sector: "العقارات" },
  { symbol: "4250.SR", name: "جبل عمر", sector: "العقارات" },
  { symbol: "4300.SR", name: "دار الأركان", sector: "العقارات" },
  { symbol: "4090.SR", name: "طيبة", sector: "العقارات" },
  { symbol: "4100.SR", name: "مكة", sector: "العقارات" },
  { symbol: "4310.SR", name: "مدينة المعرفة", sector: "العقارات" },
];
